### PR TITLE
adding flag check for javascript and polyfills

### PR DESCRIPTION
**Pull request by aintgoin2goa**
Thinking about it now this doesn't make a whole lot of sense.  Our js only runs after the polyfills are loaded so switching off polyfills will do the same as switching off javascript.  Opinions please...

### CODE REVIEW

**Comment by matthew-andrews** [comment]
Can they be decoupled?

i.e.  No polyfill service but the js will still attempt to run?  (e.g. later we might implement the switch like polyfill service vs. fixed set of polyfills?)

**Comment by matthew-andrews** [comment]
Actually that might be a nice get out of jail free card…  If polyfill service goes down we just revert to big lump static of polyfills

**Comment by aintgoin2goa** [comment]
how should I get that static lump?  call the service with ua=ie8 and save it?

**Comment by matthew-andrews** [comment]
Oh that's a good idea. @Financial-Times/origami-collaborators ?

Maybe IE9 as we've dropped IE8 now.

**Comment by triblondon** [comment]
Yes, that seems like a decent thing to do.  Polyfill service is pretty reliable though.  Heroku / Fastly, and it supports stale-on-error too.

**Comment by aintgoin2goa** [comment]
This has been sitting here for ages now and I haven't got round to it yet.  Will close this and open a new pull request when I have time to properly implement.

**Pull request closed without merging**
